In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#categorical Data

In [ ]:
fruits_N=pd.Series(["Apple","Mango","Orange","Mango","Mango"]*4)
fruits_N


0      Apple
1      Mango
2     Orange
3      Mango
4      Mango
5      Apple
6      Mango
7     Orange
8      Mango
9      Mango
10     Apple
11     Mango
12    Orange
13     Mango
14     Mango
15     Apple
16     Mango
17    Orange
18     Mango
19     Mango
dtype: object

In [ ]:
pd.unique(fruits_N)

array(['Apple', 'Mango', 'Orange'], dtype=object)

In [ ]:
pd.value_counts(fruits_N)

Mango     12
Apple      4
Orange     4
dtype: int64

In [ ]:
numbers_v=pd.Series([0,1,0,0,1,1,1,0,2,2])
dim=pd.Series(["Orange","Mango","Banana"])

In [ ]:
numbers_v

0    0
1    1
2    0
3    0
4    1
5    1
6    1
7    0
8    2
9    2
dtype: int64

In [ ]:
dim

0    Orange
1     Mango
2    Banana
dtype: object

In [ ]:
dim.take(numbers_v)

0    Orange
1     Mango
0    Orange
0    Orange
1     Mango
1     Mango
1     Mango
0    Orange
2    Banana
2    Banana
dtype: object

In [ ]:
#Categorical Extension Type in pandas


In [ ]:
fruits=['Orange','Apple','Orange','Orange']*3
Number=len(fruits)

In [ ]:
Number

12

In [ ]:
generator=np.random.default_rng(seed=12345)

In [ ]:
generator


Generator(PCG64) at 0x7F21965DEE40

In [ ]:
dataframe=pd.DataFrame({'fruit':fruits,
                        'Basket_id':np.arange(Number),
                        'count':generator.integers(3,12,size=Number),
                        'weight':generator.uniform(0,4,size=Number)},
                        columns=['Basket_id','fruit','count','weight']
                       )

In [ ]:
dataframe

Basket_id   fruit  count    weight
0           0  Orange      9  2.393235
1           1   Apple      5  0.746937
2           2  Orange     10  2.691024
3           3  Orange      5  3.767211
4           4  Orange      4  0.992983
5           5   Apple     10  3.795525
6           6  Orange      8  2.668950
7           7  Orange      9  0.383592
8           8  Orange     11  1.767359
9           9   Apple      6  3.545920
10         10  Orange     10  2.789814
11         11  Orange      5  1.305891

In [ ]:
dataframe['weight'].dtypes


dtype('float64')

In [ ]:
dataframe['fruit'].dtypes

dtype('O')

In [ ]:
fruit_cat=dataframe['fruit'].astype('category')
fruit_cat


0     Orange
1      Apple
2     Orange
3     Orange
4     Orange
5      Apple
6     Orange
7     Orange
8     Orange
9      Apple
10    Orange
11    Orange
Name: fruit, dtype: category
Categories (2, object): ['Apple', 'Orange']

In [ ]:
c=fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [ ]:
c.categories

Index(['Apple', 'Orange'], dtype='object')

In [ ]:
dict(enumerate(c.categories))

{0: 'Apple', 1: 'Orange'}

In [ ]:
dataframe['fruit']=dataframe['fruit'].astype('category')
dataframe['fruit']

0     Orange
1      Apple
2     Orange
3     Orange
4     Orange
5      Apple
6     Orange
7     Orange
8     Orange
9      Apple
10    Orange
11    Orange
Name: fruit, dtype: category
Categories (2, object): ['Apple', 'Orange']

In [ ]:
my_categories=pd.Categorical(['RR','tt','yy','bb','tt'])

In [ ]:
my_categories


['RR', 'tt', 'yy', 'bb', 'tt']
Categories (4, object): ['RR', 'bb', 'tt', 'yy']

In [ ]:
categories=['RR','tt','yy']
codes=[0,1,2,1,1]

In [ ]:
my_categories2=pd.Categorical.from_codes(codes,categories)
my_categories2

['RR', 'tt', 'yy', 'tt', 'tt']
Categories (3, object): ['RR', 'tt', 'yy']

In [ ]:
ordered_cat=pd.Categorical.from_codes(codes,categories,ordered=True)
ordered_cat

['RR', 'tt', 'yy', 'tt', 'tt']
Categories (3, object): ['RR' < 'tt' < 'yy']

In [ ]:
#Computations with Categoricals

In [ ]:
rng=np.random.default_rng(seed=12345)
draws=rng.standard_normal(1000)

In [ ]:
draws

array([-1.42382504e+00,  1.26372846e+00, -8.70661738e-01, -2.59173235e-01,
       -7.53433070e-02, -7.40884652e-01, -1.36779270e+00,  6.48892802e-01,
        3.61058113e-01, -1.95286306e+00,  2.34740965e+00,  9.68496906e-01,
       -7.59387180e-01,  9.02198274e-01, -4.66953173e-01, -6.06895187e-02,
        7.88844345e-01, -1.25666813e+00,  5.75857514e-01,  1.39897899e+00,
        1.32229806e+00, -2.99698515e-01,  9.02919341e-01, -1.62158273e+00,
       -1.58189261e-01,  4.49483932e-01, -1.34360107e+00, -8.16875907e-02,
        1.72473993e+00,  2.61815943e+00,  7.77361344e-01,  8.28633196e-01,
       -9.58988313e-01, -1.20938829e+00, -1.41229201e+00,  5.41546830e-01,
        7.51939396e-01, -6.58760320e-01, -1.22867499e+00,  2.57557768e-01,
        3.12902918e-01, -1.30811690e-01,  1.26998312e+00, -9.29624577e-02,
       -6.61508890e-02, -1.10821447e+00,  1.35956851e-01,  1.34707776e+00,
        6.11440210e-02,  7.09146003e-02,  4.33654537e-01,  2.77483660e-01,
        5.30252387e-01,  

In [ ]:
draws[:3
      ]

array([-1.42382504,  1.26372846, -0.87066174])

In [ ]:
bins=pd.qcut(draws,5)

In [ ]:
bins

[(-3.121, -0.849], (0.847, 3.211], (-3.121, -0.849], (-0.849, -0.224], (-0.224, 0.28], ..., (0.28, 0.847], (-0.224, 0.28], (-0.849, -0.224], (0.28, 0.847], (-0.849, -0.224]]
Length: 1000
Categories (5, interval[float64, right]): [(-3.121, -0.849] < (-0.849, -0.224] < (-0.224, 0.28] <
                                           (0.28, 0.847] < (0.847, 3.211]]

In [ ]:
bins=pd.qcut(draws,2)

In [ ]:
bins

[(-3.121, 0.0134], (0.0134, 3.211], (-3.121, 0.0134], (-3.121, 0.0134], (-3.121, 0.0134], ..., (0.0134, 3.211], (0.0134, 3.211], (-3.121, 0.0134], (0.0134, 3.211], (-3.121, 0.0134]]
Length: 1000
Categories (2, interval[float64, right]): [(-3.121, 0.0134] < (0.0134, 3.211]]

In [ ]:
bins=pd.qcut(draws,4)

In [ ]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [ ]:
bins=pd.qcut(draws,5,labels=["a1","a2","a3","a4","a5"])
bins

['a1', 'a5', 'a1', 'a2', 'a3', ..., 'a4', 'a3', 'a2', 'a4', 'a2']
Length: 1000
Categories (5, object): ['a1' < 'a2' < 'a3' < 'a4' < 'a5']

In [ ]:
bins.codes[:5]

array([0, 4, 0, 1, 2], dtype=int8)

In [ ]:
bins.codes[:300]

array([0, 4, 0, 1, 2, 1, 0, 3, 3, 0, 4, 4, 1, 4, 1, 2, 3, 0, 3, 4, 4, 1,
       4, 0, 2, 3, 0, 2, 4, 4, 3, 3, 0, 0, 0, 3, 3, 1, 0, 2, 3, 2, 4, 2,
       2, 0, 2, 4, 2, 2, 3, 2, 3, 3, 3, 1, 3, 0, 2, 0, 2, 3, 1, 2, 0, 0,
       3, 0, 3, 0, 0, 0, 2, 3, 0, 2, 4, 1, 1, 3, 2, 1, 0, 3, 1, 2, 0, 4,
       3, 4, 2, 3, 4, 4, 3, 2, 1, 1, 0, 3, 1, 0, 2, 4, 1, 0, 2, 3, 2, 1,
       4, 4, 2, 3, 3, 3, 4, 3, 2, 1, 1, 2, 4, 3, 2, 2, 2, 3, 0, 0, 1, 0,
       4, 2, 1, 0, 3, 1, 4, 3, 1, 3, 0, 1, 4, 3, 2, 2, 0, 0, 2, 4, 0, 3,
       3, 4, 0, 1, 2, 0, 0, 0, 2, 3, 2, 2, 1, 1, 4, 2, 2, 4, 4, 4, 3, 2,
       3, 2, 4, 3, 3, 2, 4, 0, 3, 3, 0, 4, 2, 2, 0, 4, 2, 1, 2, 3, 4, 2,
       0, 1, 0, 1, 3, 3, 2, 1, 4, 3, 4, 3, 1, 4, 0, 0, 1, 1, 1, 1, 4, 2,
       3, 0, 1, 4, 0, 4, 0, 3, 1, 2, 0, 1, 4, 1, 4, 1, 0, 2, 1, 4, 4, 4,
       3, 4, 3, 3, 1, 0, 2, 4, 4, 0, 3, 2, 0, 3, 0, 2, 4, 0, 2, 0, 1, 3,
       0, 2, 1, 1, 2, 3, 4, 3, 1, 4, 4, 0, 3, 3, 4, 3, 0, 1, 0, 2, 4, 3,
       3, 1, 0, 0, 2, 1, 1, 4, 0, 0, 1, 2, 2, 0], d

In [ ]:
bins=pd.Series(bins,name='quartile')
bins

0      a1
1      a5
2      a1
3      a2
4      a3
       ..
995    a4
996    a3
997    a2
998    a4
999    a2
Name: quartile, Length: 1000, dtype: category
Categories (5, object): ['a1' < 'a2' < 'a3' < 'a4' < 'a5']

In [ ]:
result=(pd.Series(draws)
.groupby(bins)
.agg(['count','min','max'])
.reset_index())
result

quartile  count       min       max
0       a1    200 -3.119609 -0.857259
1       a2    200 -0.846951 -0.225620
2       a3    200 -0.223639  0.280066
3       a4    200  0.280961  0.846393
4       a5    200  0.849845  3.211418

In [ ]:
result['quartile']

0    a1
1    a2
2    a3
3    a4
4    a5
Name: quartile, dtype: category
Categories (5, object): ['a1' < 'a2' < 'a3' < 'a4' < 'a5']

In [ ]:
#Categorical Methods

In [ ]:
s=pd.Series(['a','b','c','d']*4)
cat_s=s.astype('category')
cat_s

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     a
9     b
10    c
11    d
12    a
13    b
14    c
15    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
cat_s.cat.codes


0     0
1     1
2     2
3     3
4     0
5     1
6     2
7     3
8     0
9     1
10    2
11    3
12    0
13    1
14    2
15    3
dtype: int8

In [ ]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
actual_categories=['a','b','c','d','e','f']
cat_s2=cat_s.cat.set_categories(actual_categories)
cat_s2

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     a
9     b
10    c
11    d
12    a
13    b
14    c
15    d
dtype: category
Categories (6, object): ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
cat_s2.value_counts()

a    4
b    4
c    4
d    4
e    0
f    0
dtype: int64

In [ ]:
cat_s.value_counts()

a    4
b    4
c    4
d    4
dtype: int64

In [ ]:
cat_s3=cat_s[cat_s.isin(['a','b'])]
cat_s3

0     a
1     b
4     a
5     b
8     a
9     b
12    a
13    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
cat_s3.cat.remove_unused_categories()

0     a
1     b
4     a
5     b
8     a
9     b
12    a
13    b
dtype: category
Categories (2, object): ['a', 'b']