Discretization and Binning

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
 ages = [11,22,33,44,55,66,77,88,99,17,34,68]

In [ ]:
bins=[15,22,30,50,110
      ]

In [ ]:
age_catagories=pd.cut(ages,bins)

In [ ]:
age_catagories

[NaN, (15.0, 22.0], (30.0, 50.0], (30.0, 50.0], (50.0, 110.0], ..., (50, 110], (50, 110], (15, 22], (30, 50], (50, 110]]
Length: 12
Categories (4, interval[int64, right]): [(15, 22] < (22, 30] < (30, 50] < (50, 110]]

In [ ]:
age_catagories.codes

array([-1,  0,  2,  2,  3,  3,  3,  3,  3,  0,  2,  3], dtype=int8)

In [ ]:
information={"ages":[11,22,33,44,55,66,77,88,99,17,34,68],
             "range":[15,22,30,50,110,12,2,4,5,6,7,8]}


In [ ]:
df=pd.DataFrame(information)
df

ages  range
0     11     15
1     22     22
2     33     30
3     44     50
4     55    110
5     66     12
6     77      2
7     88      4
8     99      5
9     17      6
10    34      7
11    68      8

In [ ]:
age_catagories.categories

IntervalIndex([(15, 22], (22, 30], (30, 50], (50, 110]], dtype='interval[int64, right]')

In [ ]:
age_catagories.categories[0
                          ]

Interval(15, 22, closed='right')

In [ ]:
pd.value_counts(age_catagories)

(50, 110]    6
(30, 50]     3
(15, 22]     2
(22, 30]     0
dtype: int64

In [ ]:
group_names=["Junior","Adult","MiddleAged", "Seniour"]

In [ ]:
label_cut=pd.cut(ages,bins,labels=group_names)

In [ ]:
pd.value_counts(label_cut)

Seniour       6
MiddleAged    3
Junior        2
Adult         0
dtype: int64

In [ ]:
data=np.random.uniform(size=25)
data

array([0.70371925, 0.73703605, 0.67527833, 0.56047567, 0.66791165,
       0.32159832, 0.61878087, 0.07962096, 0.40868086, 0.48609019,
       0.29339672, 0.84188735, 0.65846402, 0.72912594, 0.49301254,
       0.36895485, 0.52938378, 0.45010501, 0.92823067, 0.725552  ,
       0.42572519, 0.93533498, 0.75502856, 0.46255584, 0.52458794])

In [ ]:
pd.cut(data,6,precision=3)

[(0.65, 0.793], (0.65, 0.793], (0.65, 0.793], (0.507, 0.65], (0.65, 0.793], ..., (0.365, 0.507], (0.793, 0.935], (0.65, 0.793], (0.365, 0.507], (0.507, 0.65]]
Length: 25
Categories (6, interval[float64, right]): [(0.0788, 0.222] < (0.222, 0.365] < (0.365, 0.507] <
                                           (0.507, 0.65] < (0.65, 0.793] < (0.793, 0.935]]

In [ ]:
data=np.random.standard_normal(1000)

In [ ]:
data

array([-1.48999492e-01,  7.08550570e-02, -2.53623321e+00, -2.07041793e+00,
       -5.64928449e-01,  1.37267770e-02,  4.61977484e-01, -5.63950495e-01,
        1.17849466e+00,  3.24333728e-02, -2.01654197e+00, -3.06164245e-01,
        1.67398267e+00, -1.33571244e+00,  7.95448591e-01,  3.53572541e-01,
       -5.05247706e-01,  2.28329911e-01,  1.11414307e+00, -8.56957276e-01,
        1.41022595e-01,  1.86579733e-01, -3.06413636e-01,  7.91427878e-01,
       -1.66747065e+00,  1.43602419e+00, -6.78904289e-01,  1.96112896e+00,
       -1.61388660e+00,  7.57625003e-01, -8.47771453e-02,  7.95639906e-01,
        5.69730298e-01,  5.02075437e-01,  3.66082750e-01,  3.01805570e-01,
       -1.28243451e-01, -1.01804577e+00,  7.86234642e-01, -7.12928269e-01,
        7.99167651e-02, -1.90584788e+00,  4.98905215e-01, -4.76032940e-01,
       -2.81383122e-01, -9.20841019e-01,  6.81957618e-02,  4.09619241e-01,
       -2.49878927e-01, -8.26875278e-01, -1.53977305e+00,  6.57838176e-01,
       -7.64704945e-01, -

In [ ]:
quartiles=pd.qcut(data,5,precision=4)
quartiles

[(-0.2764, 0.293], (-0.2764, 0.293], (-3.0167, -0.9108], (-3.0167, -0.9108], (-0.9108, -0.2764], ..., (0.8847, 2.9353], (-0.9108, -0.2764], (-0.2764, 0.293], (0.293, 0.8847], (0.8847, 2.9353]]
Length: 1000
Categories (5, interval[float64, right]): [(-3.0167, -0.9108] < (-0.9108, -0.2764] < (-0.2764, 0.293] <
                                           (0.293, 0.8847] < (0.8847, 2.9353]]

In [ ]:
pd.value_counts(quartiles)

(-3.0167, -0.9108]    200
(-0.9108, -0.2764]    200
(-0.2764, 0.293]      200
(0.293, 0.8847]       200
(0.8847, 2.9353]      200
dtype: int64

Decting and filtering Outliers

In [ ]:
data1=pd.DataFrame(np.random.standard_normal((1500,6)))
data1

0         1         2         3         4         5
0     0.798341  0.211557 -1.246414 -0.596975 -1.249773  0.190182
1    -0.045588 -0.212241 -0.082549  1.384742 -0.728668 -1.159771
2    -0.016747  0.136288 -0.862870  0.588475  1.261421  0.833743
3    -0.020845 -1.636085  1.581333  0.327601  0.577270 -0.439127
4    -2.418514 -1.014392 -0.200958  2.934024 -0.714469  0.596469
...        ...       ...       ...       ...       ...       ...
1495  0.782982 -0.765673  0.470058 -0.239559 -0.963265  0.926401
1496  0.331561 -0.191899 -2.418731 -0.375410 -0.004875 -0.483095
1497  0.289543 -0.968688 -0.182704  0.419777  0.101153 -1.117590
1498  0.883551  0.830460 -0.849821 -0.949880  0.286385 -3.075836
1499  0.653008  0.084031 -0.662839  2.431915  1.051328 -0.177737

[1500 rows x 6 columns]

In [ ]:
data1.describe()

0            1            2            3            4  \
count  1500.000000  1500.000000  1500.000000  1500.000000  1500.000000   
mean      0.005798     0.003403     0.019120     0.003073     0.008350   
std       0.995301     1.003253     1.030616     1.003104     1.011967   
min      -3.605635    -3.104830    -3.192688    -2.700420    -3.166456   
25%      -0.667643    -0.702521    -0.688363    -0.676594    -0.656429   
50%      -0.008580    -0.001249    -0.032564    -0.006999     0.021669   
75%       0.672789     0.737986     0.701158     0.664912     0.648864   
max       3.171642     3.927550     3.517548     3.647763     3.985369   

                 5  
count  1500.000000  
mean     -0.052730  
std       1.037594  
min      -3.739494  
25%      -0.724924  
50%      -0.044353  
75%       0.635809  
max       3.295796

In [ ]:
col=data1[4]

In [ ]:
col

0      -1.249773
1      -0.728668
2       1.261421
3       0.577270
4      -0.714469
          ...   
1495   -0.963265
1496   -0.004875
1497    0.101153
1498    0.286385
1499    1.051328
Name: 4, Length: 1500, dtype: float64

In [ ]:
col[col.abs()>2]

13      3.985369
67      2.097958
86      2.506684
94      2.338526
121     2.163880
          ...   
1438    3.105438
1447    2.356018
1454   -2.973786
1484    2.078240
1490   -2.075784
Name: 4, Length: 69, dtype: float64

In [ ]:
col[col.abs()<2]

0      -1.249773
1      -0.728668
2       1.261421
3       0.577270
4      -0.714469
          ...   
1495   -0.963265
1496   -0.004875
1497    0.101153
1498    0.286385
1499    1.051328
Name: 4, Length: 1431, dtype: float64

In [ ]:
col[col.abs()>5
    ]

Series([], Name: 4, dtype: float64)

In [ ]:
col[col.abs()<5]

0      -1.249773
1      -0.728668
2       1.261421
3       0.577270
4      -0.714469
          ...   
1495   -0.963265
1496   -0.004875
1497    0.101153
1498    0.286385
1499    1.051328
Name: 4, Length: 1500, dtype: float64

In [ ]:
data1[(data1.abs()>1).any(axis="columns")]

0         1         2         3         4         5
0     0.798341  0.211557 -1.246414 -0.596975 -1.249773  0.190182
1    -0.045588 -0.212241 -0.082549  1.384742 -0.728668 -1.159771
2    -0.016747  0.136288 -0.862870  0.588475  1.261421  0.833743
3    -0.020845 -1.636085  1.581333  0.327601  0.577270 -0.439127
4    -2.418514 -1.014392 -0.200958  2.934024 -0.714469  0.596469
...        ...       ...       ...       ...       ...       ...
1494  1.800302  0.330407  1.003918 -0.838402 -1.129056  1.012853
1496  0.331561 -0.191899 -2.418731 -0.375410 -0.004875 -0.483095
1497  0.289543 -0.968688 -0.182704  0.419777  0.101153 -1.117590
1498  0.883551  0.830460 -0.849821 -0.949880  0.286385 -3.075836
1499  0.653008  0.084031 -0.662839  2.431915  1.051328 -0.177737

[1353 rows x 6 columns]

In [ ]:
data1[data1.abs()>2]=np.sign(data1)*2
data1.describe

<bound method NDFrame.describe of              0         1         2         3         4         5
0     0.798341  0.211557 -1.246414 -0.596975 -1.249773  0.190182
1    -0.045588 -0.212241 -0.082549  1.384742 -0.728668 -1.159771
2    -0.016747  0.136288 -0.862870  0.588475  1.261421  0.833743
3    -0.020845 -1.636085  1.581333  0.327601  0.577270 -0.439127
4    -2.000000 -1.014392 -0.200958  2.000000 -0.714469  0.596469
...        ...       ...       ...       ...       ...       ...
1495  0.782982 -0.765673  0.470058 -0.239559 -0.963265  0.926401
1496  0.331561 -0.191899 -2.000000 -0.375410 -0.004875 -0.483095
1497  0.289543 -0.968688 -0.182704  0.419777  0.101153 -1.117590
1498  0.883551  0.830460 -0.849821 -0.949880  0.286385 -2.000000
1499  0.653008  0.084031 -0.662839  2.000000  1.051328 -0.177737

[1500 rows x 6 columns]>

In [ ]:
np.sign(data1).head


<bound method NDFrame.head of         0    1    2    3    4    5
0     1.0  1.0 -1.0 -1.0 -1.0  1.0
1    -1.0 -1.0 -1.0  1.0 -1.0 -1.0
2    -1.0  1.0 -1.0  1.0  1.0  1.0
3    -1.0 -1.0  1.0  1.0  1.0 -1.0
4    -1.0 -1.0 -1.0  1.0 -1.0  1.0
...   ...  ...  ...  ...  ...  ...
1495  1.0 -1.0  1.0 -1.0 -1.0  1.0
1496  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
1497  1.0 -1.0 -1.0  1.0  1.0 -1.0
1498  1.0  1.0 -1.0 -1.0  1.0 -1.0
1499  1.0  1.0 -1.0  1.0  1.0 -1.0

[1500 rows x 6 columns]>

# String Manupulation

In [ ]:
#Python Built in string methods

In [ ]:
value="a,b, guido"
value.split(",")

['a', 'b', ' guido']

In [ ]:
pieces=[x.strip() for x in value.split(",")]
pieces


['a', 'b', 'guido']

In [ ]:
first,second,third=pieces
first + " :::- " + second + " ::::-- " + third

'a :::- b ::::-- guido'

In [ ]:
":::".join(pieces)

'a:::b:::guido'

In [ ]:
"guido" in value

True

In [ ]:
"nor,mal" in value

False

In [ ]:
value.index(",")


1

In [ ]:
value.index("b")

2

In [ ]:
value.index("i")

7

In [ ]:
value

'a,b, guido'

In [ ]:
value.replace(",",":::::")

'a:::::b::::: guido'

In [ ]:
value.replace(",","-----")

'a-----b----- guido'