In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
l=[1,2,3]
l_array=np.array([1,2,3])
print(l_array)
print(l)

[1 2 3]
[1, 2, 3]


In [ ]:
data=np.array([[2.2,3.4,-7],[9,0,9.8]])

In [ ]:
data

array([[ 2.2,  3.4, -7. ],
       [ 9. ,  0. ,  9.8]])

In [ ]:
data*2

array([[  4.4,   6.8, -14. ],
       [ 18. ,   0. ,  19.6]])

In [ ]:
data+data

array([[  4.4,   6.8, -14. ],
       [ 18. ,   0. ,  19.6]])

In [ ]:
data-data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

In [ ]:
import numpy as np

datanew=[19,7.8,33,9]

In [ ]:
arr2=np.array(datanew)

In [ ]:
arr2

array([19. ,  7.8, 33. ,  9. ])

In [ ]:
datanew1=[[3,7,8,3],[5,8,3,2]]

In [ ]:
arr3=np.array(datanew1)

In [ ]:
arr3

array([[3, 7, 8, 3],
       [5, 8, 3, 2]])

In [ ]:
arr3.ndim

2

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr3.dtype

dtype('int64')

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones((1,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
arr4=np.array([2,5,8], dtype=np.float64)

In [ ]:
arr4.dtype

dtype('float64')

In [ ]:
arr=np.array([[1,2,3,4],[4,6,7,8]])

In [ ]:
arr

array([[1, 2, 3, 4],
       [4, 6, 7, 8]])

In [ ]:
arr*arr

array([[ 1,  4,  9, 16],
       [16, 36, 49, 64]])

In [ ]:
arr-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
arr+arr

array([[ 2,  4,  6,  8],
       [ 8, 12, 14, 16]])

In [ ]:
arr**2

array([[ 1,  4,  9, 16],
       [16, 36, 49, 64]])

In [ ]:
arr1=np.array([[1,2,43,5],[4,56,7,6]])

In [ ]:
arr1

array([[ 1,  2, 43,  5],
       [ 4, 56,  7,  6]])

In [ ]:

arr1>arr

array([[False, False,  True,  True],
       [False,  True, False, False]])

Basic Indexing and slicing

In [ ]:
import numpy as np

In [ ]:
arr4=np.arange(1,15)

In [ ]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr4[4]

5

In [ ]:
arr4[3:7]

array([4, 5, 6, 7])

In [ ]:
arr4[3:7]

array([3, 4, 5, 6])

In [ ]:
arr4[5:7]=44

In [ ]:
arr4

array([ 1,  2,  3,  4,  5, 44, 44,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr4_slice=arr4[5:7]
arr4_slice

array([44, 44])

In [ ]:
arr4_slice[:]=5

In [ ]:
arr4

array([ 1,  2,  3,  4,  5,  5,  5,  8,  9, 10, 11, 12, 13, 14])