In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])


1D,2D,3D Array


In [ ]:
print(a)

[1 2 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
c=np.array([[[1,2,3],[4,5,6,],[7,8,9]]],dtype=int)

In [ ]:
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#Data type


In [ ]:
c=np.array([[[1,2,3],[4,5,6,],[7,8,9]]],dtype=float)

In [ ]:
print(c)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]


In [ ]:
c=np.array([[[1,2,3],[4,5,6,],[7,8,9]]],dtype=bool)

In [ ]:
print(c)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]


In [ ]:
c=np.array([[[1,2,3],[4,5,6,],[7,8,9]]],dtype=complex)

In [ ]:
print(c)

[[[1.+0.j 2.+0.j 3.+0.j]
  [4.+0.j 5.+0.j 6.+0.j]
  [7.+0.j 8.+0.j 9.+0.j]]]


#Numpy array range(np.arange)

In [ ]:
 x=np.arange(2,13)

In [ ]:
print(x
      )

[ 2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
np.arange(10,100,15)

array([10, 25, 40, 55, 70, 85])

#Reshape
To convert value in specific row and colum




In [ ]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(1,23).reshape(11,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22]])

#Np onea and zeros

In [ ]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#Random values

In [ ]:
np.random.random((3,4))

array([[0.92954941, 0.95233766, 0.24392102, 0.17797015],
       [0.36745934, 0.08026149, 0.50424457, 0.99074551],
       [0.90986833, 0.59404457, 0.15520089, 0.620002  ]])

#For two point same distance

In [ ]:
np.linspace(10,40,60)

array([10.        , 10.50847458, 11.01694915, 11.52542373, 12.03389831,
       12.54237288, 13.05084746, 13.55932203, 14.06779661, 14.57627119,
       15.08474576, 15.59322034, 16.10169492, 16.61016949, 17.11864407,
       17.62711864, 18.13559322, 18.6440678 , 19.15254237, 19.66101695,
       20.16949153, 20.6779661 , 21.18644068, 21.69491525, 22.20338983,
       22.71186441, 23.22033898, 23.72881356, 24.23728814, 24.74576271,
       25.25423729, 25.76271186, 26.27118644, 26.77966102, 27.28813559,
       27.79661017, 28.30508475, 28.81355932, 29.3220339 , 29.83050847,
       30.33898305, 30.84745763, 31.3559322 , 31.86440678, 32.37288136,
       32.88135593, 33.38983051, 33.89830508, 34.40677966, 34.91525424,
       35.42372881, 35.93220339, 36.44067797, 36.94915254, 37.45762712,
       37.96610169, 38.47457627, 38.98305085, 39.49152542, 40.        ])

In [ ]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

#Identity Matrix


In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#Array attributes

In [ ]:
a1=np.arange(10)

In [ ]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a3=np.arange(8).reshape(2,2,2)

In [ ]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
a2=np.arange(12,dtype=float).reshape(3,4)

In [ ]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

In [ ]:
a3.shape

(2, 2, 2)

In [ ]:
a2.shape

(3, 4)

In [ ]:
a3.size

8

In [ ]:
print(a3.dtype)

int64


In [ ]:
print(a2.dtype)

float64


In [ ]:
print(a1.dtype)

int64


#As type


In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#Array operation

In [ ]:
a1=np.arange(12).reshape(3,4)

In [ ]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a2=np.arange(12).reshape(3,4)

In [ ]:
print(a2)

[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]


In [ ]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
a2**2

array([[144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676]])

In [ ]:
a1+3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [ ]:
a2-2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a2/3

array([[4.        , 4.33333333, 4.66666667, 5.        , 5.33333333],
       [5.66666667, 6.        , 6.33333333, 6.66666667, 7.        ],
       [7.33333333, 7.66666667, 8.        , 8.33333333, 8.66666667]])

#Relational Operation

In [ ]:
a2>2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
a1<1

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1==3

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1>=2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2<= 4

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

#Vector Operator

In [ ]:
a1*a2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a1+a2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1**a2

array([[           1,            1,            4,           27],
       [         256,         3125,        46656,       823543],
       [    16777216,    387420489,  10000000000, 285311670611]])

In [ ]:
a1/a2

<ipython-input-54-3ccc78f0d2eb>:1: RuntimeWarning: invalid value encountered in true_divide
  a1/a2


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#Array Function

In [ ]:
a1=np.random.random((3,3))

In [ ]:
print(a1)

[[0.31943931 0.35182299 0.42134132]
 [0.50401941 0.16522839 0.54406956]
 [0.87397184 0.77568821 0.64586556]]


In [ ]:
a1=np.round(a1*100)

In [ ]:
print(a1
      )

[[32. 35. 42.]
 [50. 17. 54.]
 [87. 78. 65.]]


In [ ]:
np.max(a1)

87.0

In [ ]:
np.min(a1)

17.0

In [ ]:
np.sum(a1)

460.0

In [ ]:
np.prod(a1)

952373298240000.0

In [ ]:
np.max(a1,axis=1)

array([42., 54., 87.])

In [ ]:
np.max(a1,axis=0)

array([87., 78., 65.])

In [ ]:
np.mean(a1)

51.111111111111114

In [ ]:
np.median(a2)

5.5

In [ ]:
np.std(a1)

21.304378498559316

In [ ]:
np.var(a1)

453.8765432098765

In [ ]:
np.exp(a1)


array([[7.89629602e+13, 1.58601345e+15, 1.73927494e+18],
       [5.18470553e+21, 2.41549528e+07, 2.83075330e+23],
       [6.07603023e+37, 7.49841700e+33, 1.69488924e+28]])

In [ ]:
np.log(a2)

<ipython-input-70-e0fbf9947be5>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.round(a1)

array([[32., 35., 42.],
       [50., 17., 54.],
       [87., 78., 65.]])

In [ ]:
np.round(np.random.random((2,3))*100)

array([[99., 20., 41.],
       [24., 87., 64.]])

#Indexing and slicing

In [ ]:
a1=np.arange(12)

In [ ]:
a2=np.arange(12).reshape(3,4)

In [ ]:
a3=np.arange(8).reshape(2,2,2)

In [ ]:
a1[-1]

11

In [ ]:
a1[0]

0

In [ ]:
a2[1]

array([4, 5, 6, 7])

In [ ]:
a1[-2]

10

In [ ]:
a2[2,3]

11

In [ ]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,1,1]

3

In [ ]:
a3[1,0,0]

4

#Slicing

In [ ]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a1[7:]

array([ 7,  8,  9, 10, 11])

In [ ]:
a1[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[2,::2]

array([ 8, 10])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [ ]:
a2[0::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1::3,0::3]

array([[4, 7]])

In [ ]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,1:,:]

array([[6, 7]])

#Herating

In [ ]:
for i in a1:
  print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
for i in a2:
  print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
for i in np.nditer(a3):
  print(iter)

<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>
<built-in function iter>


In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a3.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel

<function ndarray.ravel>

In [ ]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

#Staking

In [ ]:
np.hstack((a1,a2))

ValueError: ignored

In [ ]:
a2=np.arange(12).reshape(3,4)

In [ ]:
a3=np.arange(12).reshape(3,4)

In [ ]:
np.hstack((a2,a3))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [ ]:
np.vstack((a2,a3))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#spliting

In [ ]:
np.hsplit(a2,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.vsplit(a3,3
          )

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]