In [ ]:
import numpy as np

In [ ]:
array1=np.array([1,2,3,4,5],[6,7,8,9,0])

In [ ]:
print(array1.dtype)

int64


In [ ]:
array1.ndim

2

In [ ]:
array1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18,  0]])

In [ ]:
array1-2

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7, -2]])

In [ ]:
array1/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 0. ]])

In [ ]:
array1.shape

(2, 5)

In [ ]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
np.arange(2,11,2
          )

array([ 2,  4,  6,  8, 10])

In [ ]:
np.arange(27,dtype=float).reshape(3
                     ,3,3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [ ]:
np.arange(27,dtype=int).reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(24).reshape(2,3,4)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
array1[1:4]

array([[6, 7, 8, 9, 0]])

In [ ]:
data1=np.array([[1,2,4,6],[5,7,9,0]])
data2=np.array([[2,3,4,5],[2,5,7,8]])


In [ ]:
data1*data2

array([[ 2,  6, 16, 30],
       [10, 35, 63,  0]])

In [ ]:
data1/data2

array([[0.5       , 0.66666667, 1.        , 1.2       ],
       [2.5       , 1.4       , 1.28571429, 0.        ]])

In [ ]:
data1**data2

array([[      1,       8,     256,    7776],
       [     25,   16807, 4782969,       0]])

In [ ]:
data1>data2

array([[False, False, False,  True],
       [ True,  True,  True, False]])

In [ ]:
data1[1]

array([5, 7, 9, 0])

Indexing

In [ ]:
data1[1]

array([5, 7, 9, 0])

In [ ]:
data3=np.arange(10,60)

In [ ]:
data3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
data3[2
      ]

2

In [ ]:
data3[:

      ]=2

In [ ]:
data3

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [ ]:
data3[6:11]

array([16, 17, 18, 19, 20])

In [ ]:
data3[6:11]=33

In [ ]:
data3

array([10, 11, 12, 13, 14, 15, 33, 33, 33, 33, 33, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
data4=np.arange(27).reshape(3,3,3)

In [ ]:
data4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
data4[2,0::2,1::2]

array([[19],
       [25]])

In [ ]:
data4[2,0::2,0::2]

array([[18, 20],
       [24, 26]])

In [ ]:
data4.shape

(3, 3, 3)

In [ ]:
data4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
data4[1:,1,0:]

array([[12, 13, 14],
       [21, 22, 23]])

In [ ]:
data4[1:,1,1]

array([13, 22])

In [ ]:
names=np.array(["n","h","k","a","k","l","a"])
data5=np.array([[2,3],[4,56],[3,7],[9,6],[1,78],[6,7],[9,3]])

In [ ]:
data5

array([[ 2,  3],
       [ 4, 56],
       [ 3,  7],
       [ 9,  6],
       [ 1, 78],
       [ 6,  7],
       [ 9,  3]])

In [ ]:
data5[names=="a"]

array([[9, 6],
       [9, 3]])

In [ ]:
data5[names=="n",0:]

array([[2, 3]])

In [ ]:
names

array(['n', 'h', 'k', 'a', 'k', 'l', 'a'], dtype='<U1')

In [ ]:
names=="a"

array([False, False, False,  True, False, False,  True])

In [ ]:
m=(names=="k")|(names=="a")

In [ ]:
m

array([False, False,  True,  True,  True, False,  True])

In [ ]:
data5[m]

array([[ 3,  7],
       [ 9,  6],
       [ 1, 78],
       [ 9,  3]])

In [ ]:
m1=(names=="k") & (names=="a")

In [ ]:
m1

array([False, False, False, False, False, False, False])

In [ ]:
data5[m1]

array([], shape=(0, 2), dtype=int64)

In [ ]:
data5[names!="a"]=1

In [ ]:
data5


array([[1, 1],
       [1, 1],
       [1, 1],
       [9, 6],
       [1, 1],
       [1, 1],
       [9, 3]])

In [ ]:
a1=np.array([[1,2,3,4,5]])

In [ ]:
a1

array([[0, 0, 0, 0, 0]])

In [ ]:
a2=np.zeros((9,5))

In [ ]:
for i in range(5):
  a2[i]=i

In [ ]:
a2

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a2.T

array([[0., 1., 2., 3., 4., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4., 0., 0., 0., 0.]])

In [ ]:
ran=np.random.random((3,3))

In [ ]:
ran

array([[0.24827044, 0.10855753, 0.57249923],
       [0.56590531, 0.83386434, 0.0903347 ],
       [0.23107464, 0.78342775, 0.53195633]])

In [ ]:
r2=np.random.standard_normal(size=(2,2))

In [ ]:
r2

array([[-0.64307215, -0.57095369],
       [ 0.88368001,  1.68626038]])

In [ ]:
np.mean(r2)

0.3389786386424565

In [ ]:
np.median(r2)

0.1563631614436125

In [ ]:
np.sum(r2)

1.355914554569826